version: "3.7"
services:

  tor:
    image: trasba/tor:latest
    volumes:
      - ./hidden_service:/lib/tor/hidden_service
#      - ./tor:/etc/service/tor
      - ./conf.d:/etc/nginx/conf.d
      - ./service:/etc/service
    networks:
      - tor
    restart: unless-stopped

networks:
  tor:
